### ISSUE TITLE
312218 - [Newsroom] [UAT Testing] - Critical Pages - Fact Sheet - Line breaks on content texts

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#360]
Description: The content displays line breaks on specific parts of the page.

Legacy: https://newsroom.accenture.com/fact-sheet/
Migrated: https://tempnewsroom.accenture.com/fact-sheet

Expected: Texts are in proper format.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/c5e3b65a-7bca-4e2b-bdd5-f84aee77a234)

Actual: There are unnecessary line breaks displaying
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0c23733a-639d-432c-9839-91d0027af970)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/312218
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Please fix the content. This happens sometimes because the source content is 100% inconsistent and has NBSPs and BRs all over the place.

**Comment by amol-anand** [comment]
Also this issue is fixed.

**Comment by jjjaspher** [comment]
@amol-anand upon checking the page, it is still not aligned properly, is there a way we can fix it with authoring only?
https://main--accenture-newsroom--hlxsites.hlx.page/fact-sheet
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/cf9fd087-835a-4630-8070-7b7be39f8214)

**Expected** 
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/d3e42aa6-0639-46c4-af20-0af2fe0e30d6)
CC: @raymond-h-dev @veejayricana

**Comment by Jaykaaa** [comment]
@amol-anand Please provide your commitment date on fixing this bug. We need to fix this bug this week.

**Comment by amol-anand** [comment]
@jjjaspher there is another issue - https://github.com/hlxsites/accenture-newsroom/issues/357 that is similar to this. @ravkiran is taking a look at that one. let's continue the discussion there and close this one out.
