### ISSUE TITLE
[321856] - [Newsroom][Content Migration]https://tempnewsroom.accenture.fr/fr/news/2023/accenture-investit-3-milliards-de-dollars-dans-l-ia-pour-accelerer-la-reinvention-des-entreprises - Extra spaces on the Downloaded PDF file

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#367]
Description of the issue:  Upon fixing the issue from [BUG 67435](https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/67435) regarding the inline text link is not aligned with the content text on the downloaded file, it resulted to another issue which is having extra spaces after the first paragraph on the downloaded file.

Steps to replicate.
1. Click the Download button on the share module section.
2. Open the downloaded pdf file.
3. Check the content of the downloaded PDF file.
Legacy:  
1. https://newsroom.accenture.fr/fr/news/accenture-investit-3-milliards-de-dollars-dans-l-ia-pour-accelerer-la-r%C3%A9invention-des-entreprises.htm
2. https://newsroom.accenture.fr/fr/news/accenture-finalise-l-acquisition-de-linkbynet-l-un-des-principaux-fournisseurs-fran%C3%A7ais-de-services-cloud.htm

Migrated: 
1. https://tempnewsroom.accenture.fr/fr/news/2023/accenture-investit-3-milliards-de-dollars-dans-l-ia-pour-accelerer-la-reinvention-des-entreprises
2. https://tempnewsroom.accenture.fr/fr/news/2021/accenture-finalise-l-acquisition-de-linkbynet-l-un-des-principaux-fournisseurs-francais-de-services-cloud

Expected: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/ac9bd9b8-9966-4280-bd16-014a21259956)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/3ea40785-e092-4ef7-8e3e-a261730afb75)

Azdo link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/321856
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
This will be fixed when we re-import the content for the Geos. starting that tomorrow

**Comment by amol-anand** [comment]
related to https://github.com/hlxsites/accenture-newsroom/issues/341

**Comment by amol-anand** [comment]
This should be fixed now with the reimport. Any extra BRs added by the import script has been removed.

**Comment by jjjaspher** [comment]
Hi @amol-anand , it seems the issue still persisting. 
https://main--accenture-newsroom-fr--hlxsites.hlx.live/fr/news/2023/accenture-investit-3-milliards-de-dollars-dans-l-ia-pour-accelerer-la-reinvention-des-entreprises
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/b855b9b5-432b-4279-a65f-981e2e420b11)

**Comment by amol-anand** [comment]
this one seems like an edge case. not sure why it is giving that space. the html does not have that space. maybe it is being extra conservative when trying to figure out where the page break is.

**Comment by amol-anand** [comment]
Since this is a one-off for only this page closing it. if you see this behavior more consistently, we can reopen and take a look at what else we can do while generating PDFs.

**Comment by jjjaspher** [comment]
Hi @amol-anand, reopening this bug as there's  a report from busines that the issue is persisting.
https://newsroom.accenture.com/news/2023/accenture-to-announce-first-quarter-fiscal-2024-results
