### ISSUE TITLE
59884- [Newsroom] Newsfeed- Calendar Filter is not visible when no search result found in small devices

### ISSUE THREAD

**Issue by Rashi24** [hlxsites/accenture-newsroom#80]
Priority: 2 - High

**Steps to Reproduce:**
1. Open URL 
**Legacy newsroom page:**
Homepage: https://newsroom.accenture.com/
**Adobe Franklin migrated page:** 
Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/

2. Open dev tool
3. View in small device
4. Select date range 

**Actual (Migrated Page):** Calendar Filter is not visible when no search result found
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/4c9b4f13-7ac0-41e4-a9d2-4eee3c97d9e5)

**Expected (Legacy Newsroom Page):** Calendar Filter should be visible when no search result found
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/ce0f4238-6cdf-4db8-bac8-4c104b9be127)

| Device | iPad 5th | | Browser | Tablet_safari | | Operating System | iOS 15.0 | | Resolution | 1536 x 2048 px | | Screen size | 9.7 in - 5.8 x 7.8 in | | Viewport | 768 x 954 px | | Aspect Ratio | 4 : 3 |

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59884
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by zozo-j** [comment]
- [ ] Code Build
- [ ] Smoke Testing - Feature Branch
- [ ] For PR Approval

**Comment by Jaykaaa** [comment]
Hello @amol-anand a gentle follow up on the PR of this bug please. Thank you.

**Comment by ravkiran** [comment]
@Jaykaaa this should be working, can you please check again?

**Comment by zozo-j** [comment]
I already sent this for retest yesterday, seems still not retested by the tester.
